apiVersion: v1
kind: Service
metadata:
  name: devops-map-brasil
  namespace: semana-devops
  labels:
    app: devops-map-brasil
spec:
  type: LoadBalancer
  selector:
    app: devops-map-brasil
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
